(local leader " ")

(fn setup []
  (set vim.g.mapleader leader)
  (set vim.g.localleader leader)
  (set vim.o.number true)
  (set vim.o.signcolumn :yes)
  (set vim.o.cursorline true)
  (set vim.o.winborder :rounded)
  (set vim.o.scrolloff 10)
  (set vim.o.ignorecase true)
  (set vim.o.smartcase true)
  (set vim.o.inccommand :split)
  (set vim.o.mouse :a)
  (set vim.o.breakindent true)
  (set vim.o.undofile true)
  (set vim.o.swapfile false)
  (set vim.o.confirm true)
  (set vim.o.updatetime 250)
  (set vim.o.timeoutlen 300)
  (set vim.o.tabstop 2)
  (set vim.o.shiftwidth 2)
  (set vim.o.expandtab true)
  (set vim.o.list true)
  (set vim.o.splitright true)
  (set vim.o.splitbelow true)
  (set vim.opt.listchars {:tab "» " :trail "·" :nbsp "␣"})
  (set vim.opt.foldenable true)
  (set vim.opt.foldlevelstart 99)
  (set vim.opt.foldlevel 99)
  (set vim.opt.foldmethod :indent)
  (set vim.opt.completeopt [:menu :menuone :noselect :popup :preview])
  (vim.schedule (fn []
                  (set vim.o.clipboard :unnamedplus))))

{: setup}
