-- [nfnl] fnl/config/plugins/mini.fnl
vim.pack.add({"https://github.com/nvim-mini/mini.nvim"})
vim.pack.add({"https://github.com/nvim-mini/mini-git"})
vim.pack.add({"https://github.com/nvim-mini/mini.statuscolumn"})
vim.pack.add({"https://github.com/nvim-mini/mini.clue"})
local mini_pick = require("mini.pick")
local mini_completion = require("mini.completion")
local mini_comment = require("mini.comment")
local mini_diff = require("mini.diff")
local mini_extra = require("mini.extra")
local mini_starter = require("mini.starter")
local mini_notify = require("mini.notify")
local mini_tabline = require("mini.tabline")
local mini_hipatterns = require("mini.hipatterns")
local mini_icons = require("mini.icons")
local mini_statusline = require("mini.statusline")
local mini_indentscope = require("mini.indentscope")
local mini_statuscolumn = require("mini.statuscolumn")
local mini_cursorword = require("mini.cursorword")
local mini_clue = require("mini.clue")
local mini_cmdline = require("mini.cmdline")
local mini_trailspace = require("mini.trailspace")
local function setup()
  mini_pick.setup({})
  mini_completion.setup({})
  mini_comment.setup({})
  mini_diff.setup({})
  mini_starter.setup({})
  mini_notify.setup({})
  mini_tabline.setup({})
  mini_hipatterns.setup({})
  mini_trailspace.setup({})
  mini_statuscolumn.setup({})
  mini_indentscope.setup({})
  mini_clue.setup({triggers = {{mode = {"n", "x"}, keys = "<leader>"}}, clues = {{mode = "n", keys = "<Leader>c", desc = "+Code"}, {mode = "n", keys = "<Leader>g", desc = "+Git/Goto"}, {mode = "n", keys = "<Leader>r", desc = "+Rename"}, {mode = "n", keys = "<Leader>s", desc = "+Search"}, mini_clue.gen_clues.square_brackets, mini_clue.gen_clues.builtin_completion, mini_clue.gen_clues.g, mini_clue.gen_clues.windows}})
  mini_cmdline.setup({})
  mini_icons.setup({})
  mini_statusline.setup({})
  mini_cursorword.setup({})
  return mini_extra.setup({})
end
return {setup = setup}
